discount/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from discount.api import views
urlpatterns = patterns('products.api.views',
    url(r'products/$', views.ProductListCreateAPIView.as_view(), name='product-list'),
    #url(r'^$', 'api_root'),
    )

urlpatterns = format_suffix_patterns(urlpatterns)

discount/urls.py
from django.conf.urls import patterns, url
from discount import views
#from django.views.decorators.cache import cache_page

urlpatterns = patterns('discount.views',
    #cart
    #url(r'^cart_add/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'add'}, name='cart-add'),
    #url(r'^cart_remove/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'remove'}, name='cart-remove'),
    url(r'^cart/$', views.CartView.as_view(), name='cart-view'), #'discount/cart/cart_view.html'
    url(r'^instant_cart/$', views.CartView.as_view(), name='instant-cart-view', kwargs={'action': 'instant'}), #'discount/cart/cart_view.html'
    url(r'^cart_remove_from_cart/$', views.CartView.as_view(), kwargs={'action': 'remove'}, name='cart-remove-from-cart'),  #!!!!
    url(r'^cart_clear/$', views.CartView.as_view(), kwargs={'action': 'clear'}, name='cart-clear'),  #!!!
    url(r'^cart_remove_expired/$', views.CartView.as_view(), kwargs={'action': 'remove-expired'}, name='cart-remove-expired'), #!!!
    url(r'^cart_finish/$', views.CartView.as_view(), name='cart-finish', kwargs={'action': 'finish'} ),  #!!!
    #url(r'^cart/view/(?P<link>[a-zA-Z0-9_]{1,})/$', views.CartViewLink.as_view(), name='cart-view-link'), #'discount/cart/cart_view_link.html'
    #url(r'^cart/list/$', views.CartList.as_view(), name='cart-list'), #'discount/cart/cart_list.html'


    #cart-product
    url(r'^coupon/(?P<pk>\d+)/$', views.ProductCartView.as_view(), name='coupon-view', kwargs={'type': 'normal'}), #'discount/product/product_cart_view.html'   #!!!
    url(r'^c/(?P<pk>\d+)/(?P<uid>\d+)/(?P<pin>\d+)/$', views.ProductCartView.as_view(), name='qr-coupon-view', kwargs={'type': 'qr'}), #'discount/product/product_cart_view.html' #!!!
    #Одиночная акция, на которую мы уже подписаны. Попадаем с основной страницы акции. Выводит изменения даты, статуса, размеров и цветов с момента подписки.

    url(r'^product/pdf_view/(?P<pk>\d+)/$', views.SingleProductPDFView.as_view(), name='product-pdf-view'),  #!!!
    #PDF - аналог coupon-view


    url(r'^qr-code/(?P<data>[a-zA-Z0-9\-\/_\:\.]{1,})/$', views.coupon_qr_code_view, name='coupon-qr-code-view'), #!!!


    #product
    url(r'^product/detail/(?P<pk>\d+)/$', views.ProductDetail.as_view(), kwargs={'type': 'pk'}, name='product-detail'), #'discount/product/product_detail.html'
    url(r'^product/detail/(?P<code>[a-zA-Z0-9_]{1,})/$', views.ProductDetail.as_view(), kwargs={'type': 'code'}, name='product-detail-code'), #'discount/product/product_detail.html'
    url(r'^product/list/(?P<alias>[a-z0-9_]{1,})/$', views.ProductList.as_view(), name='product-list'), #'discount/product/product_list.html'
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product-create'), #'discount/product/product_create.html'
    url(r'^product/update/(?P<pk>\d+)/$', views.ProductCreate.as_view(), name='product-update'), #'discount/product/product_create.html'
    url(r'^generate_product_code/$', views.GenerateProductCode.as_view(), name='generate-product-code'), #!!!

    url(r'^get_product_by_code', views.GetProductByCode.as_view(), name='get-product-by-code'), #!!!
    url(r'^left_menu/(?P<alias>[a-z0-9_]{1,})/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form'), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/shop_list/$', views.ProductList.as_view(), name='product-list-shop', kwargs={'type': 'shop'}), #'discount/product/product_list.html' #!!!

    url(r'^left_menu_shop/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-shop', kwargs={'type': 'shop'}), #'discount/product/_product_list_filter_form.html' #!!!



    url(r'^product/code_list/$', views.ProductList.as_view(), name='product-list-code', kwargs={'type': 'code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-code', kwargs={'type': 'code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/finished_code_list/$', views.ProductList.as_view(), name='product-list-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_finished_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^get_available_product_types_ajax', views.GetAvailableProductTypesAjax.as_view(), name='get-available-product-types-ajax'), #!!!
    url(r'^get_available_filters_ajax', views.GetAvailableFiltersAjax.as_view(), name='get-available-filters-ajax'), #!!!


    url(r'^product/banners/(?P<pk>\d+)/$', views.ProductBannersView.as_view(),name='product-banners'), #'discount/product/product_detail.html' #!!!

    url(r'^product/start/(?P<pk>\d+)/$', views.ProductStartView.as_view(),name='product-start'), #'discount/product/product_detail.html' #!!!


    url(r'^product/change/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), name='product-change'), #'discount/product/product_detail.html' #!!!
    #url(r'^product/change/update/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), kwargs={'type': 'update'}, name='product-change-existing'), #'discount/product/product_detail.html'

    #url(r'^banner/send_to_approve/$', views.SendBannerToApproveView.as_view(), name='send-banner-to-approve'), #'discount/product/product_detail.html'
    url(r'^product/export/all/$', views.ExportProductsToCsvView.as_view(), name='product-export-all'), #'discount/product/product_list.html' #!!!

    url(r'^subscribed_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'subscribed'}, name='subscribed_to_product'), #!!!
    url(r'^cart_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'cart'}, name='cart_to_product'), #!!!
    url(r'^bought_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'bought'}, name='bought_to_product'), #!!!

    url(r'^product_stat_save/(?P<pk>\d+)/$', views.ProductStatSaveView.as_view(), name='product-stat-save'),

    url(r'^products_stat/$', views.ProductsStatView.as_view(), name='products-stat'), #'discount/product/product_list.html' #!!!

    #product_to_cart
    #url(r'^ptc_subscribe_view/(?P<pk>\d+)/$', views.PTCSubscribe.as_view(), name='ptc-subscribe-view'),

    #url(r'^cart_actions/(?P<pk>\d+)/$', views.CartActions.as_view(), name='cart-actions'),
    url(r'^ptc_add/(?P<pk>\d+)/$', views.PtcAdd.as_view(), name='ptc-add'), #!!!
    url(r'^ptc_subscribe/(?P<pk>\d+)/$', views.PtcSubscribe.as_view(), name='ptc-subscribe'), #!!!
    url(r'^coupon_status/(?P<pk>\d+)/$', views.CouponStatus.as_view(), name='coupon-status'), #!!!


    #general
    url(r'^$', views.MainPage.as_view(), name='main-page'), #'discount/general/main_page.html'

   #shop
    url(r'^shop/detail/(?P<pk>\d+)/$', views.ShopDetail.as_view(), name='shop-detail'), #'discount/shop/shop_detail.html' #!!!
    url(r'^shop/list/$', views.ShopList.as_view(), name='shop-list'), #'discount/shop/shop_list.html'

    url(r'^shop/create/$', views.ShopCreate.as_view(), name='shop-create'), #'discount/shop/shop_list.html' #!!!
    #url(r'^shop/update/(?P<pk>\d+)/$', views.ShopUpdate.as_view(), name='shop-update'),
    url(r'^shop/update/(?P<pk>\d+)/$', views.ShopCreate.as_view(), name='shop-update'), #'discount/product/product_create.html' #!!!



    #user
    url(r'^ajax_login/$', views.DiscountLoginView.as_view(), name='login'), #'discount/user/_login.html' #!!!
    url(r'^login/$', views.DiscountFullLoginView.as_view(), name='full-login'), #'discount/user/_login.html'
    url(r'^signup/$', views.DiscountSignupView.as_view(), name='signup'), #'discount/user/_login.html'
    url(r'^cart_login/$', views.DiscountCartLoginView.as_view(), name='cart-login'),
    url(r'^cart_signup/$', views.DiscountCartSignupView.as_view(), name='cart-signup'),
    url(r'^user/$', views.UserDetail.as_view(), name='user-detail'), #'discount/user/user_detail.html' #!!!
    url(r'^shops_to_users_confirm/$', views.ShopsToUsersConfirm.as_view(), name='shops-to-users-confirm'), #'discount/user/user_detail.html' #!!!
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change-password'), #'discount/user/_login.html' #!!!


    #static
    url(r'^contacts', views.ContactsPageView.as_view(), name='contacts-page'), #'discount/user/_login.html'
    url(r'^help', views.HelpPageView.as_view(), name='help-page'), #'discount/user/_login.html'
    url(r'^shop_offer', views.ShopOfferView.as_view(), name='shop-offer'), #'discount/user/_login.html'
    url(r'^shop_instructions', views.ShopInstructionsView.as_view(), name='shop-instructions'),



    #adm
    url(r'^tatamo_manager/$', views.TatamoManagerPageView.as_view(), name='tatamo-manager-page'),   #!!!
    url(r'^load_products/$', views.AdmLoadProductsView.as_view(), name='load-products'),   #!!!
    url(r'^monitor/$', views.AdmMonitorView.as_view(), name='monitor'),   #!!!

    url(r'^product/tatamo_list/$', views.ProductList.as_view(), name='product-list-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_tatamo/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product_tatamo_manager_approve/(?P<pk>\d+)/$', views.ProductTatamoManagerApproveView.as_view(), name='product-tatamo-manager-approve'),  #!!!

    url(r'^shops_monitor/$', views.AdmShopsMonitorView.as_view(), name='shops-monitor'),   #!!!

    url(r'^users_monitor/$', views.AdmUsersMonitorView.as_view(), name='users-monitor'),   #!!!

    url(r'^product_doubles_monitor/$', views.AdmProductDoublesMonitorView.as_view(), name='product-doubles-monitor'),   #!!!

kulik/urls.py
from django.conf.urls import patterns, include, url
#from rest_framework import routers, serializers, viewsets
from django.contrib.auth.models import User

"""
url()
https://docs.djangoproject.com/en/1.7/ref/urls/
url(regex, view, kwargs=None, name=None, prefix='')
You can use the url() function, instead of a tuple, as an argument to patterns(). This is convenient if you want to specify a name without the optional extra arguments dictionary. For example:

urlpatterns = patterns('',
    url(r'^index/$', index_view, name="main-view"),
    ...
)
This function takes five arguments, most of which are optional:

url(regex, view, kwargs=None, name=None, prefix='')



include()
https://docs.djangoproject.com/en/1.7/ref/urls/#include
https://docs.djangoproject.com/en/1.7/topics/http/urls
include(module[, namespace=None, app_name=None])
include(pattern_list)
include((pattern_list, app_namespace, instance_namespace))
A function that takes a full Python import path to another URLconf module that should be “included” in this place.
Optionally, the application namespace and instance namespace where the entries will be included into can also be
specified.

include() also accepts as an argument either an iterable that returns URL patterns or a 3-tuple
containing such iterable plus the names of the application and instance namespaces.

Parameters:
module – URLconf module (or module name)
namespace (string) – Instance namespace for the URL entries being included
app_name (string) – Application namespace for the URL entries being included
pattern_list – Iterable of URL entries as returned by patterns()
app_namespace (string) – Application namespace for the URL entries being included
instance_namespace (string) – Instance namespace for the URL entries being included

application namespace - простраство имен приложения. У нескольких приложений может быть view с именем index
чтобы reverse мог их различить, например:
В kulik.urls указано
url(r'^polls/', include('polls.urls', namespace="polls")),
url(r'^posts/', include('posts.urls', namespace="posts")),

В posts.urls
url(r'^$', views.index, name='index'),
В polls.urls тоже
url(r'^$', views.index, name='index'),

Мы передаем в reverse('polls:index') или reverse('posts:index'), чтобы их различить.

instance namespace
По умолчанию = application namespace.
У приложения может быть несколько instances. Если их несколько, то текущее должно быть указано в:
"If there is a current application defined, Django finds and returns the URL resolver for that instance.
The current application can be specified as an attribute on the template context - applications that expect to
have multiple deployments should set the current_app attribute on any Context or RequestContext that is used to
render a template.
The current application can also be specified manually as an argument
to the django.core.urlresolvers.reverse() function."
то есть в объекте Context или RequestContext. Также может быть указано вручную в функции reverse().

"""

from django.contrib import admin
from kulik import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from discount.sitemaps import sitemaps
from django.views.decorators.cache import cache_page




urlpatterns = patterns('',


    url(r'^contact_form/', include('contact_form.urls', namespace="contact_form")),

    url(r'^admin/', include(admin.site.urls)),

    (r'^accounts/', include('allauth.urls')),


    url(r'^', include('discount.urls', namespace='discount')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^sitemap\.xml$', cache_page(60 * 60)(sitemap), {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
    #url(r'^discount/api/', include('discount.api.urls')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'^', include(router.urls)),

    #legacy
#url(r'^markitup/', include('markitup.urls')),
#url(r'^polls/', include('polls.urls', namespace="polls")),
 #url(r'^users/', include('users.urls', namespace="users")),
#url(r'^$', views.main, name='kulik'),
  #url(r'^posts/', include('posts.urls', namespace="posts")),
    #url(r'^mixintest/', include('mixintest.urls', namespace="mixintest")),
    #url(r'^history/', include('history.urls', namespace="history")),
    #url(r'^dreams/', include('dreams.urls', namespace='dreams')),
    #url(r'^dreams/api/', include('dreams.api_urls')),

    #url(r'^tester/', include('tester.urls', namespace='tester')),


)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

#urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))

discount/api/views.py
from rest_framework.generics import ListCreateAPIView
from discount.api import serializers
from discount.models import Product


class ProductListCreateAPIView(ListCreateAPIView):
    model = Product
    serializer_class = serializers.ProductSerializer

discount/templates/discount/widgets/_cart_add_product_script.html
{% load compress %}
{% compress js %}
<script>

$(document).on('click', '.action-submit', function (caller) {
       $(this).closest('form').find('.submit-type').val($(this).attr('name'));
   $('#submit-type').val('to-approve');
   });


$(function(){
    //var frm = $('.unsubscribe-form');
    $(document).on('submit', '.ptc-action-form', function (caller) {
        $.ajax({
            type: 'post',
            url: $(caller.currentTarget).attr('action'),
            data: $(caller.currentTarget).serialize(),
            success: function (data) {
                if (data.status != 1) {
                    location.href = data.redirect_to;
                } else {
                    $(caller.currentTarget).closest('.add-to-cart-outer, .get-code').html(data.html);
                    $('#cart-count').html(data.count);
                    $('.code-list-menu').text(data.code_list_menu);
                    $('.finished-list-menu').text(data.finished_list_menu);
                    var pk = data.pk;
                    $('#ptc-add-block-' + pk).html('');

                    if (pk > 0) {

                        $.ajax({
                            type: 'post',
                            url: ("/coupon_status/" + pk + '/'),
                            data: {},
                            success: function (inner_data) {
                                $('#coupon-status-' + pk).html(inner_data);
                                $('#ptc-add-block-' + pk).html('');
                            },
                            error: function (inner_data) {

                            }
                        });
                    }


                }
            },
            error: function(data) {
                //$('.add-to-favourite').html(data);
            }
        });
        return false;
    });
});
</script>
{% endcompress %}

discount/templates/discount/widgets/_coupon.html
{% load discount_tags %}
{% load static %}

<div class="coupon-container" style="line-heigth: 1.5; color: #6b7777; width: 80%; margin: 0 auto; font-family: Arial, Sans-serif; font-size: 12px; 
margin-top: 35px;" >


	<div class="img" style="width: 192px; height: auto; margin: 0 auto;" >
		<img src="{% get_site_url %}{% static "discount/images/logo3.png" %}"> </div>
	
   
    <div style="margin-top: 40px; width: 100%; overflow: hidden; clear: both;">


    
		
		
      

		
		<div id="product-{{ product.pk }}" class="{{ product.get_class }} product" style="line-height: 1.5; 
		overflow: hidden; clear: both; padding: 30px; border: 1px solid #e3e8ea;">
			<img style="float: left; margin: 0 20px 20px 0; " src="{% get_site_url %}{{ qr_url }}">

			<div style="display: inline-block; border-bottom: 1px solid #000; padding-bottom: 5px; margin-bottom: 10px;">
			<div style=" display: inline-block; margin: 10px 10px 0 0; font-size: 18px; font-weight: bold; 
			color: #000; text-transform: uppercase">
				{{ product.brand }}
			</div>
			
			<h7  style="display: inline-block; margin-top: 5px; font-size: 14px; font-weight: normal; ">
			{{ product }}</h7>
			</div>	<br />		
			
			<div style="display: inline-block;">Цена по акции: <span style="font-size: 16px; font-weight: bold; color: #000;"> {{ product.stock_price }} руб.</span></div>
			<div style="display: inline-block; border: 1px solid #e3e8ea; padding: 1px 3px;" >Скидка: {{ product.percent }} %</div>
			<div style="margin-top: 5px;"> Промокод: <span style="color: #000;">{{ code }}</span></div>

			<div style="clear: both">
{{ product.body }}
			</div>
        
       
			

            {% comment %}
        <div class="code" style=" padding: 5px 10px;
                                 display: inline-block;
                                 margin-bottom: 10px;">
                                 
            {% get_product_code product %}</div>
            {% endcomment %}
            
            
        <div class="end-date" style="margin-bottom: 10px; margin-top: 30px;">
			Дата окончания акции: <span style="color: #000; display: inline-block;">   {% get_history_value product 'end_date' %} </span> 
            </div>
        <div class="status" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;">Статус:</span><span style="color: #000; display: inline-block;">    {% get_history_value product 'status' %} </span> 
            </div>

        {% if product.sizes_man.all.count > 0 %}
            <div class="sizes" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;"> Размеры: </span> <span style="color: #000; display: inline-block;">{% get_history_m2m_values product 'sizes_man' %} </span>
      </div>
        {% endif %}

        {% if product.sizes_woman.all.count > 0 %}
        <div class="sizes" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;"> Размеры: </span> <span style="color: #000; display: inline-block;">{% get_history_m2m_values product 'sizes_woman' %} </span>
      </div>
        {% endif %}

        {% if product.sizes_shoes.all.count > 0 %}
        <div class="sizes" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;"> Размеры: </span> <span style="color: #000; display: inline-block;">{% get_history_m2m_values product 'sizes_shoes' %} </span>
      </div>
          {% endif %}

{% if product.sizes_childs.all.count > 0 %}
        <div class="sizes" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;"> Размеры: </span> <span style="color: #000; display: inline-block;">{% get_history_m2m_values product 'sizes_childs' %} </span>
      </div>
{% endif %}

    {% if product.colors.all.count > 0 %}
        <div class="colors" style="margin-bottom: 10px;">
			<span style="margin-right: 5px;"> Цвета:</span><span style="color: #000; display: inline-block;"> {% get_history_m2m_values product 'colors' %} </span> 
      </div>
      {% endif %}

   
			<div class="shop" style="margin-top: 40px; font-size: 12px; border-top: 1px dotted #e3e8ea; 
									 border-pbottom: 1px dotted #e3e8ea; padding: 30px 0 10px 0;">
				<div style="margin-bottom: 10px; font-size: 16px; font-weight: bold; color: #000;">{{ product.shop }}</div>
				{% if product.shop.custom_adress %}
				<div style="margin-bottom: 10px;" >Адрес: {{ product.shop.custom_adress }}</div>
				{% endif %}
				{% if product.shop.site %}
				<div style="margin-bottom: 10px;" >Сайт: {{ product.shop.site }}</div>
				{% endif %}
				<div style="margin-bottom: 10px;" >
				{% for phone in product.shop.phones.all %}
				Телефон: {{ phone }} <br />
				{% endfor %}
				</div>
				{% if product.shop.work_time %}
				<div style="margin-bottom: 10px;" >Время работы: {{ product.shop.work_time }}</div>
				{% endif %}

			</div>
   
   
    </div> 

  



</div>

		   <ul style="margin: 40px 0 40px;
			   padding: 40px 40px;
			   background: #F0F4F5 none repeat scroll 0% 0%;
			   line-height: 2;
			   color: #000;
			   font-size: 11px;">

{% for condition in product.product_conditions %}
			   <li  style="display: block; line-height: 1.2; margin-bottom: 10px; "  data-icon="&#8250"  >
{{ condition }}
</li>

{% endfor %}
</ul>
<div  style="width: 100%; text-align: right; margin-top: 20px;">
	<a style="display: inline-block; margin-left: 15px; margin-bottom: 10px; color: #000; text-decoration: underline;" href="{% get_site_url %}{{ product.get_absolute_url }}">На страницу акции</a>
	<a style="display: inline-block; margin-left: 15px; margin-bottom: 10px; color: #000; text-decoration: underline;" href="{% get_site_url %}{{ product.get_pdf_url }}">Открыть купон в формате PDF</a>
	<a style="display: inline-block; margin-left: 15px; margin-bottom: 10px; color: #000; text-decoration: underline;"href="{% get_site_url %}{{ product.get_coupon_url }}">Открыть купон</a>
</div>

</div>

discount/templates/discount/widgets/_product_coupon_status.html
<div class="coupon-status" id="coupon-status-{{ product.pk }}">
{% if subscribed %}

<div class="status">   
    <label>Промокод: </label>
        <div class="code">{{ code }}</div>
        <div class="coupon-links">
			<a href="{% url 'discount:product-pdf-view' product.pk %}"><span>Открыть купон в формате PDF</span></a>
			<a href="{% url 'discount:coupon-view' product.pk %}"><span>Открыть купон</span></a>
        </div>
</div>


    {% elif show_bought %}
    <div class="status">
    Вы приобрели товар по этой акции
	</div>
{% endif %}
</div>

discount/templates/discount/widgets/_product_info_main.html
{% load discount_tags %}
{% load cache %}
{% cache 2419200 product_info_main_1 product.pk %}


<div class="item category-item col-md-3 col-sm-4 col-xs-4">
	<div class="wrapper clearfix">

	{% if not product.ad %}
		<a class="product" href="{{ product.get_absolute_url }}">
			{% endif %}
				<div class="product-image">
		
			<img src="{{ product.get_main_image.thumb204 }}">

		</div>
	
	
	{% if not product.ad %}
		<div class="description clearfix">
			<div class="brand">{{ product.brand }}</div>
			<div class="name">{{ product }}</div>
           
			<div class="price"><span class="normal-price"> {{ product.normal_price }} руб</span><span class="current-price"> {{ product.stock_price }} руб </span></div>
			<span class="percent">-{{ product.percent }}%</span>
		</div>


	</a>	
{% endif %}
</div>
</div>
  {% endcache %}

discount/templates/discount/widgets/_product_tatamo_manager_approve.html
{% load discount_tags %}
<div>
<label>Комментарий магазина:</label>
{{ product.shop_comment }}
</div>
<div>
<label>Стартовать после согласования: </label>
{{ product.start_after_approve|bool_as_yes }}
</div>
<form id="product-tatamo-manager-approve-form-{{ product.pk }}" class="product-tatamo-manager-approve-form" method="post" action="{% url 'discount:product-tatamo-manager-approve' product.pk %}">
{% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

discount/templates/discount/widgets/get_product_by_code.html
{% load compress %}
<div class="search-inner hidden popup">
<form method="post" id="get-product-by-code-form" class="clearfix" action="{% url 'discount:get-product-by-code' %}">
    
    
    <div class="field">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    
    <div class="search-button"> <input type="submit" value="Найти"> </div> 

    
</form>

<div id="get-product-by-code-form-error"></div>

</div>
{% compress js %}
<script>
	
	$(function() {
		$(".search-icon").hover(function () {
			$(".search-inner").toggleClass("hidden");
		});		
	});
	
    $(function() {
    var frm = $('#get-product-by-code-form');
    frm.on('submit', function (event, machineGenerated) {
        if(machineGenerated) return;
        event.preventDefault();
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                if (data.status == 1) {
                    $("#get-product-by-code-form-error").html("");
                    if (event.isDefaultPrevented()) {
                        frm.trigger('submit', [true]);
                    }
                }
                else {
                $("#get-product-by-code-form-error").html(data.message);
                }
            }   ,
            error: function(data) {
                $("#get-product-by-code-form-error").html('Акция не найдена');
            }
        });
        //return false;
    });
    });
</script>
{% endcompress %}