discount/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from discount.api import views
urlpatterns = patterns('products.api.views',
    url(r'products/$', views.ProductListCreateAPIView.as_view(), name='product-list'),
    #url(r'^$', 'api_root'),
    )

urlpatterns = format_suffix_patterns(urlpatterns)

discount/urls.py
from django.conf.urls import patterns, url
from discount import views
#from django.views.decorators.cache import cache_page

urlpatterns = patterns('discount.views',
    #cart
    #url(r'^cart_add/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'add'}, name='cart-add'),
    #url(r'^cart_remove/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'remove'}, name='cart-remove'),
    url(r'^cart/$', views.CartView.as_view(), name='cart-view'), #'discount/cart/cart_view.html'
    url(r'^instant_cart/$', views.CartView.as_view(), name='instant-cart-view', kwargs={'action': 'instant'}), #'discount/cart/cart_view.html'
    url(r'^cart_remove_from_cart/$', views.CartView.as_view(), kwargs={'action': 'remove'}, name='cart-remove-from-cart'),  #!!!!
    url(r'^cart_clear/$', views.CartView.as_view(), kwargs={'action': 'clear'}, name='cart-clear'),  #!!!
    url(r'^cart_remove_expired/$', views.CartView.as_view(), kwargs={'action': 'remove-expired'}, name='cart-remove-expired'), #!!!
    url(r'^cart_finish/$', views.CartView.as_view(), name='cart-finish', kwargs={'action': 'finish'} ),  #!!!
    #url(r'^cart/view/(?P<link>[a-zA-Z0-9_]{1,})/$', views.CartViewLink.as_view(), name='cart-view-link'), #'discount/cart/cart_view_link.html'
    #url(r'^cart/list/$', views.CartList.as_view(), name='cart-list'), #'discount/cart/cart_list.html'


    #cart-product
    url(r'^coupon/(?P<pk>\d+)/$', views.ProductCartView.as_view(), name='coupon-view', kwargs={'type': 'normal'}), #'discount/product/product_cart_view.html'   #!!!
    url(r'^c/(?P<pk>\d+)/(?P<uid>\d+)/(?P<pin>\d+)/$', views.ProductCartView.as_view(), name='qr-coupon-view', kwargs={'type': 'qr'}), #'discount/product/product_cart_view.html' #!!!
    #Одиночная акция, на которую мы уже подписаны. Попадаем с основной страницы акции. Выводит изменения даты, статуса, размеров и цветов с момента подписки.

    url(r'^product/pdf_view/(?P<pk>\d+)/$', views.SingleProductPDFView.as_view(), name='product-pdf-view'),  #!!!
    #PDF - аналог coupon-view


    url(r'^qr-code/(?P<data>[a-zA-Z0-9\-\/_\:\.]{1,})/$', views.coupon_qr_code_view, name='coupon-qr-code-view'), #!!!


    #product
    url(r'^product/detail/(?P<pk>\d+)/$', views.ProductDetail.as_view(), kwargs={'type': 'pk'}, name='product-detail'), #'discount/product/product_detail.html'
    url(r'^product/detail/(?P<code>[a-zA-Z0-9_]{1,})/$', views.ProductDetail.as_view(), kwargs={'type': 'code'}, name='product-detail-code'), #'discount/product/product_detail.html'
    url(r'^product/list/(?P<alias>[a-z0-9_]{1,})/$', views.ProductList.as_view(), name='product-list'), #'discount/product/product_list.html'
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product-create'), #'discount/product/product_create.html'
    url(r'^product/update/(?P<pk>\d+)/$', views.ProductCreate.as_view(), name='product-update'), #'discount/product/product_create.html'
    url(r'^generate_product_code/$', views.GenerateProductCode.as_view(), name='generate-product-code'), #!!!

    url(r'^get_product_by_code', views.GetProductByCode.as_view(), name='get-product-by-code'), #!!!
    url(r'^left_menu/(?P<alias>[a-z0-9_]{1,})/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form'), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/shop_list/$', views.ProductList.as_view(), name='product-list-shop', kwargs={'type': 'shop'}), #'discount/product/product_list.html' #!!!

    url(r'^left_menu_shop/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-shop', kwargs={'type': 'shop'}), #'discount/product/_product_list_filter_form.html' #!!!



    url(r'^product/code_list/$', views.ProductList.as_view(), name='product-list-code', kwargs={'type': 'code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-code', kwargs={'type': 'code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/finished_code_list/$', views.ProductList.as_view(), name='product-list-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_finished_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^get_available_product_types_ajax', views.GetAvailableProductTypesAjax.as_view(), name='get-available-product-types-ajax'), #!!!
    url(r'^get_available_filters_ajax', views.GetAvailableFiltersAjax.as_view(), name='get-available-filters-ajax'), #!!!


    url(r'^product/banners/(?P<pk>\d+)/$', views.ProductBannersView.as_view(),name='product-banners'), #'discount/product/product_detail.html' #!!!

    url(r'^product/start/(?P<pk>\d+)/$', views.ProductStartView.as_view(),name='product-start'), #'discount/product/product_detail.html' #!!!


    url(r'^product/change/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), name='product-change'), #'discount/product/product_detail.html' #!!!
    #url(r'^product/change/update/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), kwargs={'type': 'update'}, name='product-change-existing'), #'discount/product/product_detail.html'

    #url(r'^banner/send_to_approve/$', views.SendBannerToApproveView.as_view(), name='send-banner-to-approve'), #'discount/product/product_detail.html'
    url(r'^product/export/all/$', views.ExportProductsToCsvView.as_view(), name='product-export-all'), #'discount/product/product_list.html' #!!!

    url(r'^subscribed_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'subscribed'}, name='subscribed_to_product'), #!!!
    url(r'^cart_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'cart'}, name='cart_to_product'), #!!!
    url(r'^bought_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'bought'}, name='bought_to_product'), #!!!

    url(r'^product_stat_save/(?P<pk>\d+)/$', views.ProductStatSaveView.as_view(), name='product-stat-save'),

    url(r'^products_stat/$', views.ProductsStatView.as_view(), name='products-stat'), #'discount/product/product_list.html' #!!!

    #product_to_cart
    #url(r'^ptc_subscribe_view/(?P<pk>\d+)/$', views.PTCSubscribe.as_view(), name='ptc-subscribe-view'),

    #url(r'^cart_actions/(?P<pk>\d+)/$', views.CartActions.as_view(), name='cart-actions'),
    url(r'^ptc_add/(?P<pk>\d+)/$', views.PtcAdd.as_view(), name='ptc-add'), #!!!
    url(r'^ptc_subscribe/(?P<pk>\d+)/$', views.PtcSubscribe.as_view(), name='ptc-subscribe'), #!!!
    url(r'^coupon_status/(?P<pk>\d+)/$', views.CouponStatus.as_view(), name='coupon-status'), #!!!


    #general
    url(r'^$', views.MainPage.as_view(), name='main-page'), #'discount/general/main_page.html'

   #shop
    url(r'^shop/detail/(?P<pk>\d+)/$', views.ShopDetail.as_view(), name='shop-detail'), #'discount/shop/shop_detail.html' #!!!
    url(r'^shop/list/$', views.ShopList.as_view(), name='shop-list'), #'discount/shop/shop_list.html'

    url(r'^shop/create/$', views.ShopCreate.as_view(), name='shop-create'), #'discount/shop/shop_list.html' #!!!
    #url(r'^shop/update/(?P<pk>\d+)/$', views.ShopUpdate.as_view(), name='shop-update'),
    url(r'^shop/update/(?P<pk>\d+)/$', views.ShopCreate.as_view(), name='shop-update'), #'discount/product/product_create.html' #!!!



    #user
    url(r'^ajax_login/$', views.DiscountLoginView.as_view(), name='login'), #'discount/user/_login.html' #!!!
    url(r'^login/$', views.DiscountFullLoginView.as_view(), name='full-login'), #'discount/user/_login.html'
    url(r'^signup/$', views.DiscountSignupView.as_view(), name='signup'), #'discount/user/_login.html'
    url(r'^cart_login/$', views.DiscountCartLoginView.as_view(), name='cart-login'),
    url(r'^cart_signup/$', views.DiscountCartSignupView.as_view(), name='cart-signup'),
    url(r'^user/$', views.UserDetail.as_view(), name='user-detail'), #'discount/user/user_detail.html' #!!!
    url(r'^shops_to_users_confirm/$', views.ShopsToUsersConfirm.as_view(), name='shops-to-users-confirm'), #'discount/user/user_detail.html' #!!!
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change-password'), #'discount/user/_login.html' #!!!


    #static
    url(r'^contacts', views.ContactsPageView.as_view(), name='contacts-page'), #'discount/user/_login.html'
    url(r'^help', views.HelpPageView.as_view(), name='help-page'), #'discount/user/_login.html'
    url(r'^shop_offer', views.ShopOfferView.as_view(), name='shop-offer'), #'discount/user/_login.html'
    url(r'^shop_instructions', views.ShopInstructionsView.as_view(), name='shop-instructions'),



    #adm
    url(r'^tatamo_manager/$', views.TatamoManagerPageView.as_view(), name='tatamo-manager-page'),   #!!!
    url(r'^load_products/$', views.AdmLoadProductsView.as_view(), name='load-products'),   #!!!
    url(r'^monitor/$', views.AdmMonitorView.as_view(), name='monitor'),   #!!!

    url(r'^product/tatamo_list/$', views.ProductList.as_view(), name='product-list-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_tatamo/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product_tatamo_manager_approve/(?P<pk>\d+)/$', views.ProductTatamoManagerApproveView.as_view(), name='product-tatamo-manager-approve'),  #!!!

    url(r'^shops_monitor/$', views.AdmShopsMonitorView.as_view(), name='shops-monitor'),   #!!!

    url(r'^users_monitor/$', views.AdmUsersMonitorView.as_view(), name='users-monitor'),   #!!!

    url(r'^product_doubles_monitor/$', views.AdmProductDoublesMonitorView.as_view(), name='product-doubles-monitor'),   #!!!

kulik/urls.py
from django.conf.urls import patterns, include, url
#from rest_framework import routers, serializers, viewsets
from django.contrib.auth.models import User

"""
url()
https://docs.djangoproject.com/en/1.7/ref/urls/
url(regex, view, kwargs=None, name=None, prefix='')
You can use the url() function, instead of a tuple, as an argument to patterns(). This is convenient if you want to specify a name without the optional extra arguments dictionary. For example:

urlpatterns = patterns('',
    url(r'^index/$', index_view, name="main-view"),
    ...
)
This function takes five arguments, most of which are optional:

url(regex, view, kwargs=None, name=None, prefix='')



include()
https://docs.djangoproject.com/en/1.7/ref/urls/#include
https://docs.djangoproject.com/en/1.7/topics/http/urls
include(module[, namespace=None, app_name=None])
include(pattern_list)
include((pattern_list, app_namespace, instance_namespace))
A function that takes a full Python import path to another URLconf module that should be “included” in this place.
Optionally, the application namespace and instance namespace where the entries will be included into can also be
specified.

include() also accepts as an argument either an iterable that returns URL patterns or a 3-tuple
containing such iterable plus the names of the application and instance namespaces.

Parameters:
module – URLconf module (or module name)
namespace (string) – Instance namespace for the URL entries being included
app_name (string) – Application namespace for the URL entries being included
pattern_list – Iterable of URL entries as returned by patterns()
app_namespace (string) – Application namespace for the URL entries being included
instance_namespace (string) – Instance namespace for the URL entries being included

application namespace - простраство имен приложения. У нескольких приложений может быть view с именем index
чтобы reverse мог их различить, например:
В kulik.urls указано
url(r'^polls/', include('polls.urls', namespace="polls")),
url(r'^posts/', include('posts.urls', namespace="posts")),

В posts.urls
url(r'^$', views.index, name='index'),
В polls.urls тоже
url(r'^$', views.index, name='index'),

Мы передаем в reverse('polls:index') или reverse('posts:index'), чтобы их различить.

instance namespace
По умолчанию = application namespace.
У приложения может быть несколько instances. Если их несколько, то текущее должно быть указано в:
"If there is a current application defined, Django finds and returns the URL resolver for that instance.
The current application can be specified as an attribute on the template context - applications that expect to
have multiple deployments should set the current_app attribute on any Context or RequestContext that is used to
render a template.
The current application can also be specified manually as an argument
to the django.core.urlresolvers.reverse() function."
то есть в объекте Context или RequestContext. Также может быть указано вручную в функции reverse().

"""

from django.contrib import admin
from kulik import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from discount.sitemaps import sitemaps
from django.views.decorators.cache import cache_page




urlpatterns = patterns('',


    url(r'^contact_form/', include('contact_form.urls', namespace="contact_form")),

    url(r'^admin/', include(admin.site.urls)),

    (r'^accounts/', include('allauth.urls')),


    url(r'^', include('discount.urls', namespace='discount')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^sitemap\.xml$', cache_page(60 * 60)(sitemap), {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
    #url(r'^discount/api/', include('discount.api.urls')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'^', include(router.urls)),

    #legacy
#url(r'^markitup/', include('markitup.urls')),
#url(r'^polls/', include('polls.urls', namespace="polls")),
 #url(r'^users/', include('users.urls', namespace="users")),
#url(r'^$', views.main, name='kulik'),
  #url(r'^posts/', include('posts.urls', namespace="posts")),
    #url(r'^mixintest/', include('mixintest.urls', namespace="mixintest")),
    #url(r'^history/', include('history.urls', namespace="history")),
    #url(r'^dreams/', include('dreams.urls', namespace='dreams')),
    #url(r'^dreams/api/', include('dreams.api_urls')),

    #url(r'^tester/', include('tester.urls', namespace='tester')),


)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

#urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))

discount/api/views.py
from rest_framework.generics import ListCreateAPIView
from discount.api import serializers
from discount.models import Product


class ProductListCreateAPIView(ListCreateAPIView):
    model = Product
    serializer_class = serializers.ProductSerializer

discount/templates/discount/product/_product_filter_params.html
{% load discount_tags %}
{% with filter_param_names=product.get_all_filter_params %}
                            {% for param_name, param_label in filter_param_names %}
                            {%  with param_values=product|get_attr:param_name %}
                             {% if param_values %}
                            <div class="item">
                                <span class="label">{{ param_label }}:</span>
                             {% for param_value in param_values %}

                                <div class="list inline-b">

                                    {{ param_value }}

                                </div>

                                {% endfor %}
                             </div>
                             {% endif %}
                                {% endwith %}


                            {% endfor %}
                            {% endwith %}

discount/templates/discount/product/_subscribed_to_product.html
<h2>{{ title }}</h2>
<table>
<tr><th>Имя</th><th>Промокод</th><th>Время подписки</th></tr>
    {% for ptc in ptcs %}
<tr>
     <td>{{ ptc.user.first_name }}</td>
    <td>{{ ptc.promocode }}</td>
    <td>
    {% if ptc.subscription_time %}
    {{ ptc.subscription_time }}
{% endif %}
</td>
</tr>
{% endfor %}
</table>

discount/templates/discount/product/product_detail.html
{% extends 'discount/base/base.html' %}
{% load discount_tags %}
{% load cache %}
{% load compress %}

{% block content %}
  {% cache 2419200 product_detail_1 product.pk %}
    <div id="product-details" class="row">
        <div class="col-md-10">
			<div class="product item row">
				<div class="col-md-4 col-sm-5 col-xs-4 image-wrapper">
                    {% include "discount/product/_product_detail_slider.html" %}
                </div>

                <div class="col-md-8 col-sm-7 col-xs-8 product-content">

                    <div class="row head">
                        <div class="col-md-9 ">
							
							<div class="name inline-b">
								{{ product }}
							</div>



							<div class="percent inline-b">{{ product.percent }}% скидка</div>
							<div class="brand">
								{{ product.brand }}
							</div>

                        </div>

                        <div class="col-md-3 shop right-al">
                            <a href = "{{ product.shop.get_absolute_url }}">{{ product.shop.title }}</a>
                        </div>
                    </div>
					<hr class="bold"></hr>

                    <div class="body clearfix">
                        
						<div class="prices inline-b">
                            <span class="price normal-price">
                                {{ product.normal_price }}руб
                            </span>
                            <span class="price stock-price">
								{{ product.stock_price }}руб
                            </span>
                        </div>
                        
                        <div class="dates inline-b right">
							<span class="date inline-b" data-icon="&#xe081;">

                                до<span class="hilighted"> {{ product.end_date }}

                                </span></span>
							<span class="date inline-b" data-icon="&#xe018;">

                                <span class="hilighted">
                                       {% endcache %}
                            {% get_days_left product %}

                              {% cache 2419200 product_detail_2 product.pk %}
                                </span></span>

                        </div>  
                    </div>

                    <div class="row about">
                        <div class="col-md-12">
                            
							<div class="descript">
                            
                            <div class="item">


                                <div class="text">
                                    {{ product.body|linebreaks }}
                                </div>

                                {% if product.compound %}
                                <span class="label">Состав:</span>

                                <div class="list inline-b"> {{ product.compound }}</div>   
                            {% endif %}
                            </div>

                                  {% if product.link %}


                                <div class="list inline-b shop"> <a href="{{ product.get_link }}">Ссылка на страницу товара на сайте магазина</a></div>
                               {% endif %}

                      {% include 'discount/product/_product_filter_params.html' %}


{% comment %}
                            <div class="item">
                                <span class="label">Размеры:</span>
                                <div class="list inline-b"><ul class="sizes">
                                    {% for dress_size in product.dress_sizes.all %}
                                    <li class="size">
                                        {{ dress_size }}
                                    </li>
                                    {% endfor %}
                                    </ul>
                                </div> 
                            </div>
                         {% endcomment %}

							</div>
{% endcache %}
                            {% if user.is_simple_user %}
                            {% ptc_add_form product%}
                            {% ptc_subscribe_form product%}
                            {% product_coupon_status product%}
                            {% endif %}
                             {% if manage_url %}

							<div class="white"><a class="button" href="{{ manage_url }}">Редактировать</a></div>
                            <div class="white"><a class="button" href="{{ product.get_banners_url }}">Управление баннерами</a></div>
                            {% if product.status in changer_statuses %}

							<div class="white"><a class="button" href="{% url 'discount:product-change' product.pk %}">Создать заявку на изменение</a></div>
                            {% if changer.status_text %}
                                <div class="request-status"><label>Текущий статус заявки: </label>{{ changer.status_text }}</div>
                               {% endif %}
                            {% endif %}

                                      {% if shop_tatamo_manager_approve %}
                            {% product_tatamo_manager_approve product %}
                            {% endif %}

                             {% if product.status in approved_statuses %}

                              <div class="to-start-now">
                              <form method="post" action="{% url 'discount:product-start' product.pk %}">
                                  {% csrf_token %}
								  <input type="submit" value="Стартовать акцию немедленно">
                              </form>
                              {% if product.to_pay_in_day  %}
                                  <div id="to-pay-warning">Со счета будет списано {{ product.to_pay_in_day }} за размещение на главной странице!</div>
                               {% endif %}
                              </div>


                             {% endif %}

                             {% if product.status in active_statuses and product.to_pay_tomorrow %}
							<div class="to-pay-warning">
                              <label>К оплате завтра:</label> {{ product.to_pay_tomorrow }}
                              </div>


                             {% endif %}


                        {% endif %}


                        </div>
                    </div>


                </div>
               




            </div> 

            <div class="row">
               
               
				<div class="col-md-12">
					{% comment %}
					{% for image in product.images.all %}
					<div>
						<a href="{{ product.get_absolute_url }}"><img src="/media/{{ image.image }}"></a>
					</div>
					{% endfor %}
					{% endcomment %}

						{% if manage_url %}


                            	{% if users_subscribed %}
						<div class="subscribed" id="subscribed-block">
                                    На акцию подписано {{ users_subscribed }} пользователей <button class="subscribed-button" id="subscribed-button">Посмотреть</button>
					</div>
							{% endif %}

							{% if carts_count %}
                                <div class="subscribed" id="cart-block">
						Акция в корзине {{ carts_count }} пользователей <button class="subscribed-button" id="cart-button">Посмотреть</button>
					</div>
							{% endif %}

                     		{% if bought_count %}
						<div class="subscribed" id="bought-block">
                                Товар по акции приобрели {{ bought_count }} пользователей <button class="subscribed-button" id="bought-button">Посмотреть</button>
					</div>
							{% endif %}


                          	{% if user.is_tatamo_manager %}
						<table>
                        <tr>
        <th>Всего посещений</th><th>Посещений незарегистрированными пользователями</th><th>Посещений зарегистрированными пользователями</th>
        <th>Всего посетителей</th><th>Гостей</th><th>Пользователей</th>
    </tr>
                            <tr>
                                <td>{{ product.stat_all_in_period.count }}</td>
                                <td>{{ product.stat_guests_in_period.count }}</td>
                                <td>{{ product.stat_users_in_period.count }}</td>
                                <td>{{ product.stat_unique_all_in_period.count }}</td>
                                <td>{{ product.stat_unique_guests_in_period.count }}</td>
                                <td>{{ product.stat_unique_users_in_period.count }}</td>

                        </tr>
                        </table>
							{% endif %}

                        {% endif %}


				</div>
               
               
                <div class="col-md-12"><div id="comments-block">

					<div class="title"><h1> Комментарии <span>({{ comments.count }})</span></h1> <hr></hr> </div>
                    {% if comment_form %}
                    <div class="full-comment-block">
                    <input type="button" value="+ Прокомментировать" id="comment-button">

					<div id="comment-block" class="clearfix">
						<form id="comment-form" method="post" class="clearfix hidden">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <input type="submit" value="Отправить комментарий">
                        </form>
                    </div>
                   </div>
                {% else %}
					<div class="guest-comment"><div class="wrapper"  data-icon="">Для того, чтобы оставлять комментарии, необходимо <a href="{% url 'discount:full-login' %}">войти под учетной записью</a> или <a href="{% url 'discount:signup' %}">зарегистрироваться</a></div></div>
                {% endif %}
                   

                   
                    {% for comment in comments %}
                    <div class="comment">
                        <span class="user">{{ comment.name }}</span>
                        <span class="date">{{ comment.created }}</span>
                        <p class="comment-body">{{ comment.body }}</p>
                    </div>
                    {% endfor %}
                    </div>
                  
                    

                    {% if comments.count > 0 %}
                    {% include 'discount/general/_pager.html' %}
                    {% endif %}


                </div> </div>

<ul class="conditions">
{% for condition in product.product_conditions %}
<li>
	<span>{{ condition }}</span>
</li>

{% endfor %}
</ul>

        </div>

{% compress js %}
        <script>
           $(function() {
            $('#comment-button').click(function(){
                var frm = $('#comment-form');
                frm.toggleClass('hidden');
            });


        $('.subscribed-button').click(function(e){
            var id = this.id;
            if (id == 'subscribed-button'){
              var url = '{% url 'discount:subscribed_to_product' product.pk %}';
              var target = $('#subscribed-block');
            }
            else if (id == 'cart-button'){
             var url = '{% url 'discount:cart_to_product' product.pk %}';
              var target = $('#cart-block');
            }

             else if (id == 'bought-button'){
             var url = '{% url 'discount:bought_to_product' product.pk %}';
              var target = $('#bought-block');
            }

                $.ajax({
                    type: 'POST',//$(frm).attr('method'),
                    url: url,
                    //data: url_data,
                    success: function (data) {
                    target.html(data);
                    },
                    error: function (data) {

                    }
                });

        });

               {% if save_product_stat %}

        $.ajax({
                    type: 'POST',//$(frm).attr('method'),
                    url: '{%  url 'discount:product-stat-save' product.pk %}',
                    //data: url_data,
                    success: function (data) {
                    },
                    error: function (data) {
                    }
                });

               {% endif %}

           });
        </script>
{% endcompress %}
        {% endblock content %}

        {% block sidebar_right %}
        <div id="sidebar-right" class="col-md-2">

            {% shop_info %}


{% cache 60 * 30 related_products product.pk %}
{% with related_products=product.available_related_products  %}
{% if related_products.count > 0 %}
               <div class="shop-products">
	<div class="title"><h4><a href="{{ shop_url }} ">Связанные акции:</a></h4></div>
<div class="products-list clearfix">
{% for related_product in product.related_products.all %}
<div class="item">
	<a href='{{ related_product.related_product.get_absolute_url }}'><img src="{{ related_product.related_product.get_main_image.thumb120 }}"><div class="name">{{ related_product.related_product }}</div></a>
</div>
{% endfor %}
</div>
</div>
{% endif %}
{% endwith %}
{% endcache %}



{% shop_products %}
<div class="shop-products">
<div class="title"><h4>Поделиться в соцсетях</h4></div>
<script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script><div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="small" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,gplus" data-yashareTheme="counter" data-yashareTitle="{{ product }}" data-yashareLink="{% get_site_url %}{{ product.get_absolute_url }}" data-yashareDescription="Магазины и производители дарят только посетителям tatamo.ru уникальные промо-коды на скидку. Проект стартовал 1 августа, так что предложений будет все больше и больше." data-yashareImage="{% get_site_url %}{{ product.get_main_image.thumb300 }}"></div>
</div>











        </div></div>
{% endblock %}