discount/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from discount.api import views
urlpatterns = patterns('products.api.views',
    url(r'products/$', views.ProductListCreateAPIView.as_view(), name='product-list'),
    #url(r'^$', 'api_root'),
    )

urlpatterns = format_suffix_patterns(urlpatterns)

discount/urls.py
from django.conf.urls import patterns, url
from discount import views
#from django.views.decorators.cache import cache_page

urlpatterns = patterns('discount.views',
    #cart
    #url(r'^cart_add/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'add'}, name='cart-add'),
    #url(r'^cart_remove/(?P<pk>\d+)/$', views.AddProductToCart.as_view(), kwargs={'action': 'remove'}, name='cart-remove'),
    url(r'^cart/$', views.CartView.as_view(), name='cart-view'), #'discount/cart/cart_view.html'
    url(r'^instant_cart/$', views.CartView.as_view(), name='instant-cart-view', kwargs={'action': 'instant'}), #'discount/cart/cart_view.html'
    url(r'^cart_remove_from_cart/$', views.CartView.as_view(), kwargs={'action': 'remove'}, name='cart-remove-from-cart'),  #!!!!
    url(r'^cart_clear/$', views.CartView.as_view(), kwargs={'action': 'clear'}, name='cart-clear'),  #!!!
    url(r'^cart_remove_expired/$', views.CartView.as_view(), kwargs={'action': 'remove-expired'}, name='cart-remove-expired'), #!!!
    url(r'^cart_finish/$', views.CartView.as_view(), name='cart-finish', kwargs={'action': 'finish'} ),  #!!!
    #url(r'^cart/view/(?P<link>[a-zA-Z0-9_]{1,})/$', views.CartViewLink.as_view(), name='cart-view-link'), #'discount/cart/cart_view_link.html'
    #url(r'^cart/list/$', views.CartList.as_view(), name='cart-list'), #'discount/cart/cart_list.html'


    #cart-product
    url(r'^coupon/(?P<pk>\d+)/$', views.ProductCartView.as_view(), name='coupon-view', kwargs={'type': 'normal'}), #'discount/product/product_cart_view.html'   #!!!
    url(r'^c/(?P<pk>\d+)/(?P<uid>\d+)/(?P<pin>\d+)/$', views.ProductCartView.as_view(), name='qr-coupon-view', kwargs={'type': 'qr'}), #'discount/product/product_cart_view.html' #!!!
    #Одиночная акция, на которую мы уже подписаны. Попадаем с основной страницы акции. Выводит изменения даты, статуса, размеров и цветов с момента подписки.

    url(r'^product/pdf_view/(?P<pk>\d+)/$', views.SingleProductPDFView.as_view(), name='product-pdf-view'),  #!!!
    #PDF - аналог coupon-view


    url(r'^qr-code/(?P<data>[a-zA-Z0-9\-\/_\:\.]{1,})/$', views.coupon_qr_code_view, name='coupon-qr-code-view'), #!!!


    #product
    url(r'^product/detail/(?P<pk>\d+)/$', views.ProductDetail.as_view(), kwargs={'type': 'pk'}, name='product-detail'), #'discount/product/product_detail.html'
    url(r'^product/detail/(?P<code>[a-zA-Z0-9_]{1,})/$', views.ProductDetail.as_view(), kwargs={'type': 'code'}, name='product-detail-code'), #'discount/product/product_detail.html'
    url(r'^product/list/(?P<alias>[a-z0-9_]{1,})/$', views.ProductList.as_view(), name='product-list'), #'discount/product/product_list.html'
    url(r'^product/create/$', views.ProductCreate.as_view(), name='product-create'), #'discount/product/product_create.html'
    url(r'^product/update/(?P<pk>\d+)/$', views.ProductCreate.as_view(), name='product-update'), #'discount/product/product_create.html'
    url(r'^generate_product_code/$', views.GenerateProductCode.as_view(), name='generate-product-code'), #!!!

    url(r'^get_product_by_code', views.GetProductByCode.as_view(), name='get-product-by-code'), #!!!
    url(r'^left_menu/(?P<alias>[a-z0-9_]{1,})/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form'), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/shop_list/$', views.ProductList.as_view(), name='product-list-shop', kwargs={'type': 'shop'}), #'discount/product/product_list.html' #!!!

    url(r'^left_menu_shop/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-shop', kwargs={'type': 'shop'}), #'discount/product/_product_list_filter_form.html' #!!!



    url(r'^product/code_list/$', views.ProductList.as_view(), name='product-list-code', kwargs={'type': 'code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-code', kwargs={'type': 'code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product/finished_code_list/$', views.ProductList.as_view(), name='product-list-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_finished_code/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-finished-code', kwargs={'type': 'finished-code'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^get_available_product_types_ajax', views.GetAvailableProductTypesAjax.as_view(), name='get-available-product-types-ajax'), #!!!
    url(r'^get_available_filters_ajax', views.GetAvailableFiltersAjax.as_view(), name='get-available-filters-ajax'), #!!!


    url(r'^product/banners/(?P<pk>\d+)/$', views.ProductBannersView.as_view(),name='product-banners'), #'discount/product/product_detail.html' #!!!

    url(r'^product/start/(?P<pk>\d+)/$', views.ProductStartView.as_view(),name='product-start'), #'discount/product/product_detail.html' #!!!


    url(r'^product/change/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), name='product-change'), #'discount/product/product_detail.html' #!!!
    #url(r'^product/change/update/(?P<pk>\d+)/$', views.ProductChangeView.as_view(), kwargs={'type': 'update'}, name='product-change-existing'), #'discount/product/product_detail.html'

    #url(r'^banner/send_to_approve/$', views.SendBannerToApproveView.as_view(), name='send-banner-to-approve'), #'discount/product/product_detail.html'
    url(r'^product/export/all/$', views.ExportProductsToCsvView.as_view(), name='product-export-all'), #'discount/product/product_list.html' #!!!

    url(r'^subscribed_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'subscribed'}, name='subscribed_to_product'), #!!!
    url(r'^cart_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'cart'}, name='cart_to_product'), #!!!
    url(r'^bought_to_product/(?P<pk>\d+)/$', views.SubsribedToProductView.as_view(), kwargs={'action': 'bought'}, name='bought_to_product'), #!!!

    url(r'^product_stat_save/(?P<pk>\d+)/$', views.ProductStatSaveView.as_view(), name='product-stat-save'),

    url(r'^products_stat/$', views.ProductsStatView.as_view(), name='products-stat'), #'discount/product/product_list.html' #!!!

    #product_to_cart
    #url(r'^ptc_subscribe_view/(?P<pk>\d+)/$', views.PTCSubscribe.as_view(), name='ptc-subscribe-view'),

    #url(r'^cart_actions/(?P<pk>\d+)/$', views.CartActions.as_view(), name='cart-actions'),
    url(r'^ptc_add/(?P<pk>\d+)/$', views.PtcAdd.as_view(), name='ptc-add'), #!!!
    url(r'^ptc_subscribe/(?P<pk>\d+)/$', views.PtcSubscribe.as_view(), name='ptc-subscribe'), #!!!
    url(r'^coupon_status/(?P<pk>\d+)/$', views.CouponStatus.as_view(), name='coupon-status'), #!!!


    #general
    url(r'^$', views.MainPage.as_view(), name='main-page'), #'discount/general/main_page.html'

   #shop
    url(r'^shop/detail/(?P<pk>\d+)/$', views.ShopDetail.as_view(), name='shop-detail'), #'discount/shop/shop_detail.html' #!!!
    url(r'^shop/list/$', views.ShopList.as_view(), name='shop-list'), #'discount/shop/shop_list.html'

    url(r'^shop/create/$', views.ShopCreate.as_view(), name='shop-create'), #'discount/shop/shop_list.html' #!!!
    #url(r'^shop/update/(?P<pk>\d+)/$', views.ShopUpdate.as_view(), name='shop-update'),
    url(r'^shop/update/(?P<pk>\d+)/$', views.ShopCreate.as_view(), name='shop-update'), #'discount/product/product_create.html' #!!!



    #user
    url(r'^ajax_login/$', views.DiscountLoginView.as_view(), name='login'), #'discount/user/_login.html' #!!!
    url(r'^login/$', views.DiscountFullLoginView.as_view(), name='full-login'), #'discount/user/_login.html'
    url(r'^signup/$', views.DiscountSignupView.as_view(), name='signup'), #'discount/user/_login.html'
    url(r'^cart_login/$', views.DiscountCartLoginView.as_view(), name='cart-login'),
    url(r'^cart_signup/$', views.DiscountCartSignupView.as_view(), name='cart-signup'),
    url(r'^user/$', views.UserDetail.as_view(), name='user-detail'), #'discount/user/user_detail.html' #!!!
    url(r'^shops_to_users_confirm/$', views.ShopsToUsersConfirm.as_view(), name='shops-to-users-confirm'), #'discount/user/user_detail.html' #!!!
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change-password'), #'discount/user/_login.html' #!!!


    #static
    url(r'^contacts', views.ContactsPageView.as_view(), name='contacts-page'), #'discount/user/_login.html'
    url(r'^help', views.HelpPageView.as_view(), name='help-page'), #'discount/user/_login.html'
    url(r'^shop_offer', views.ShopOfferView.as_view(), name='shop-offer'), #'discount/user/_login.html'
    url(r'^shop_instructions', views.ShopInstructionsView.as_view(), name='shop-instructions'),



    #adm
    url(r'^tatamo_manager/$', views.TatamoManagerPageView.as_view(), name='tatamo-manager-page'),   #!!!
    url(r'^load_products/$', views.AdmLoadProductsView.as_view(), name='load-products'),   #!!!
    url(r'^monitor/$', views.AdmMonitorView.as_view(), name='monitor'),   #!!!

    url(r'^product/tatamo_list/$', views.ProductList.as_view(), name='product-list-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/product_list.html' #!!!
    url(r'^left_menu_tatamo/$', views.ProductListFilterForm.as_view(), name='product-list-filter-form-tatamo', kwargs={'type': 'tatamo'}), #'discount/product/_product_list_filter_form.html' #!!!

    url(r'^product_tatamo_manager_approve/(?P<pk>\d+)/$', views.ProductTatamoManagerApproveView.as_view(), name='product-tatamo-manager-approve'),  #!!!

    url(r'^shops_monitor/$', views.AdmShopsMonitorView.as_view(), name='shops-monitor'),   #!!!

    url(r'^users_monitor/$', views.AdmUsersMonitorView.as_view(), name='users-monitor'),   #!!!

    url(r'^product_doubles_monitor/$', views.AdmProductDoublesMonitorView.as_view(), name='product-doubles-monitor'),   #!!!

kulik/urls.py
from django.conf.urls import patterns, include, url
#from rest_framework import routers, serializers, viewsets
from django.contrib.auth.models import User

"""
url()
https://docs.djangoproject.com/en/1.7/ref/urls/
url(regex, view, kwargs=None, name=None, prefix='')
You can use the url() function, instead of a tuple, as an argument to patterns(). This is convenient if you want to specify a name without the optional extra arguments dictionary. For example:

urlpatterns = patterns('',
    url(r'^index/$', index_view, name="main-view"),
    ...
)
This function takes five arguments, most of which are optional:

url(regex, view, kwargs=None, name=None, prefix='')



include()
https://docs.djangoproject.com/en/1.7/ref/urls/#include
https://docs.djangoproject.com/en/1.7/topics/http/urls
include(module[, namespace=None, app_name=None])
include(pattern_list)
include((pattern_list, app_namespace, instance_namespace))
A function that takes a full Python import path to another URLconf module that should be “included” in this place.
Optionally, the application namespace and instance namespace where the entries will be included into can also be
specified.

include() also accepts as an argument either an iterable that returns URL patterns or a 3-tuple
containing such iterable plus the names of the application and instance namespaces.

Parameters:
module – URLconf module (or module name)
namespace (string) – Instance namespace for the URL entries being included
app_name (string) – Application namespace for the URL entries being included
pattern_list – Iterable of URL entries as returned by patterns()
app_namespace (string) – Application namespace for the URL entries being included
instance_namespace (string) – Instance namespace for the URL entries being included

application namespace - простраство имен приложения. У нескольких приложений может быть view с именем index
чтобы reverse мог их различить, например:
В kulik.urls указано
url(r'^polls/', include('polls.urls', namespace="polls")),
url(r'^posts/', include('posts.urls', namespace="posts")),

В posts.urls
url(r'^$', views.index, name='index'),
В polls.urls тоже
url(r'^$', views.index, name='index'),

Мы передаем в reverse('polls:index') или reverse('posts:index'), чтобы их различить.

instance namespace
По умолчанию = application namespace.
У приложения может быть несколько instances. Если их несколько, то текущее должно быть указано в:
"If there is a current application defined, Django finds and returns the URL resolver for that instance.
The current application can be specified as an attribute on the template context - applications that expect to
have multiple deployments should set the current_app attribute on any Context or RequestContext that is used to
render a template.
The current application can also be specified manually as an argument
to the django.core.urlresolvers.reverse() function."
то есть в объекте Context или RequestContext. Также может быть указано вручную в функции reverse().

"""

from django.contrib import admin
from kulik import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from discount.sitemaps import sitemaps
from django.views.decorators.cache import cache_page




urlpatterns = patterns('',


    url(r'^contact_form/', include('contact_form.urls', namespace="contact_form")),

    url(r'^admin/', include(admin.site.urls)),

    (r'^accounts/', include('allauth.urls')),


    url(r'^', include('discount.urls', namespace='discount')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^sitemap\.xml$', cache_page(60 * 60)(sitemap), {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
    #url(r'^discount/api/', include('discount.api.urls')),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'^', include(router.urls)),

    #legacy
#url(r'^markitup/', include('markitup.urls')),
#url(r'^polls/', include('polls.urls', namespace="polls")),
 #url(r'^users/', include('users.urls', namespace="users")),
#url(r'^$', views.main, name='kulik'),
  #url(r'^posts/', include('posts.urls', namespace="posts")),
    #url(r'^mixintest/', include('mixintest.urls', namespace="mixintest")),
    #url(r'^history/', include('history.urls', namespace="history")),
    #url(r'^dreams/', include('dreams.urls', namespace='dreams')),
    #url(r'^dreams/api/', include('dreams.api_urls')),

    #url(r'^tester/', include('tester.urls', namespace='tester')),


)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

#urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))

discount/api/views.py
from rest_framework.generics import ListCreateAPIView
from discount.api import serializers
from discount.models import Product


class ProductListCreateAPIView(ListCreateAPIView):
    model = Product
    serializer_class = serializers.ProductSerializer

discount/templates/discount/shop/shop_create.html
{% extends 'discount/base/base.html' %}
{% load discount_tags %}
{% load compress %}
{% block content %}
    {% if status_text %}
    <label>Статус:</label>
    {{ status_text }}
    {% endif %}
{{ form.non_field_errors }}
    <form enctype="multipart/form-data" action="{{ action_url }}" method="post" class="shop-create-form form" id="shop-create-form">
{% csrf_token %}
{{ form.media }}


  	<div class="item">
    {{ form.title.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.title.errors }}
    {{ form.title }}

		</div>
	</div>


	<div class="item">
    {{ form.image.label_tag }}
		<div class="field inline-b  wrapper">
            <div class="prompt">Изображение размером 300x300 точек.</div>
			{{ form.image.errors }}
    <div class="added-img">{{ form.image }}</div>
	
		</div>
	</div>


          <div class="inline-b-t"><div class="comment">Пожалуйста, укажите, какие бренды необходимо добавить магазину, в форме "Добавление брендов", перечислив их через запятую. <br />
			   Они станут доступны после обработки менеджером Tatamo.</div></div>
        <div class="item">
    {{ form.add_brands.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.add_brands.errors }}
      {{ form.add_brands }}

		</div>
	</div>




   {% if form.instance.pk %}
        <div class="brands item">
   <label>Доступные бренды:</label>
	   <div class="inline-b-t">

     {% for brand in brands %}
	  <div class="brand-item">{{ brand }}</div>
{% endfor %}
 {% if brands_count == 0 %}
     <div class="errorlist">Для магазина не доступно ни одного бренда.</div>
 {% endif %}
		   </div>

</div>
    {% endif %}

   	<div class="item">
    {{ form.site.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.site.errors }}
     {{ form.site }}
	
		</div>
	</div>


     	<div class="item">
    {{ form.body.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.body.errors }}
    {{ form.body }}

		</div>
	</div>


   	<div class="item">
    {{ form.work_time.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.work_time.errors }}
     {{ form.work_time }}
	
		</div>
	</div>

       	<div class="item">
    {{ form.city.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.city.errors }}
    {{ form.city }}
	
		</div>
	</div>

       	<div class="item">
    {{ form.custom_adress.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.custom_adress.errors }}
     {{ form.custom_adress }}
	
		</div>
	</div>





    {{ phone_formset.management_form }}
    {{ phone_formset.non_form_errors }}
    {% for form in phone_formset %}
    <p>
    {{ form.phone.label_tag }}
    {{ form.phone.errors }}
    {{ form.phone }}
    {% comment %}
    {{ form.DELETE|label_with_classes:'phone-delete-label' }}
    {{ form.DELETE.errors }}
    {{ form.DELETE }}
    {% endcomment %}
    {{ form.id }}
    {{ form.shop }}
    </p>
    {% endfor %}

<div class="{{ user_formset_cls }}">
<div class="inline-b-t">
<div class="comment">
Пожалуйста, перечислите здесь пользователей, у которых будут права на изменение данных о магазине и размещение акций от имени магазина.
Себя указывать не обязательно, Вы будете добавлены автоматически.
</div></div>
{{ user_formset.management_form }}
    {{ user_formset.non_form_errors }}
    {% for form in user_formset %}
    <p>
    {{ form.user.label_tag }}
    {{ form.user.errors }}
    {{ form.user|field_with_classes:'user-field' }}
    {{ form.id }}
    {{ form.shop }}
    {{ form.confirmed }}
    </p>
    {% endfor %}
</div>


        <div class="inline-b-t">
<div class="comment">
Комментарий будет виден только Вам и менеджеру Татамо.
</div></div>
    <div class="item">
    {{ form.shop_comment.label_tag }}


		<div class="field inline-b  wrapper">
			{{ form.shop_comment.errors }}
      {{ form.shop_comment }}

		</div>
	</div>

    <div class="item">
    {{ form.tatamo_comment.label_tag }}
		<div class="field inline-b  wrapper">
			{{ form.tatamo_comment.errors }}
      {{ form.tatamo_comment }}

		</div>
	</div>


<input type="hidden" name="submit-type">

        {{ form.hashed }}
{% if show_save_button %}
<input type="submit" class="to-save inline-b" name="to-save" value="Сохранить">
{% endif %}
    {% if show_submit_button %}
    <input type="submit" class="to-approve inline-b" name="to-approve" id="to-approve" value="Отправить на согласование">
{% endif %}
</form>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  {% compress js %}
   <script>

  $(function() {
    var availableTags = [
        {% for login in logins %}
            "{{ login }}",
        {% endfor %}

    ];
    $( ".user-field" ).autocomplete({
      source: availableTags
    });
  });
  </script>
{% endcompress %}

{% endblock content %}

discount/templates/discount/shop/shop_detail.html
{% extends 'discount/base/base.html' %}
{% load discount_tags %}

{% block content %}


<div id="shop-details" class="row">

    <div class="col-md-12">

		{% if edit_link %}
		<a class="btn" href="{{ edit_link }}">Редактировать</a>
		<label>Статус:</label>{{ shop.status_text }}
        <div><a href="{% url 'discount:product-export-all' %}">Выгрузить все акции магазина в CSV</a></div>

        {% endif %}
       
        <div class="row"><div class="col-md-12">
           <div class="shop-info">
            <div class="row">
            <div class="col-md-3 col-sm-4 image-wrapper">
                <img src="{{ shop.image.thumb300 }}">
            </div>
            <div class="col-md-9 col-sm-8">
                <h5>{{ shop }}</h5>
                <div class="shop-contacts">
                   
				{% shop_link shop %}

                    <span>{{ shop.body|linebreaks }}</span>

                    {% if shop.use_custom_adress %}
                    {% if shop.custom_adress %}
					<p class="adress"  data-icon="&#xe096;">
					<span>{{ shop.custom_adress|linebreaks }}</span>
                     {% endif %}
					</p> 
                    {% else %}
					<p class="adress" data-icon="&#xe096;">
                    <span>
                    {{ shop.city }}
                    {{ shop.region }}
                    {{ shop.area }}
                    {{ shop.street }}
                    {{ shop.house }}
                    {{ shop.building }}
                    {{ shop.flat }}
                    {{ shop.index }}
                    {{ shop.settlement }}
					</span>
                    {% endif %}
                    </p>
                    {% if shop.phones.all.exists %}
					<p class="phone" data-icon="&#xe048;">
					<span>
                    {% for phone in shop.phones.all %}
                    {{ phone }} <br />
                    {% endfor %}
					</span>
                    {% endif %}
                    </p>
                  
                {% if shop.work_time %}
          <p class="time">Время работы: {{ shop.work_time|linebreaks }}</p>
        {% endif %}
                </div>
            </div>
            </div>
            </div>
        </div></div>

        <div class="row shop-item item-list category-main">
            {% for product in products %}
            {% product_info_main product %}
            {% endfor %}
             
        </div>

    </div>

</div>







{% include 'discount/general/_pager.html' %}

{% endblock content %}

discount/templates/discount/shop/shop_list.html
{% extends 'discount/base/base.html' %}
{% load discount_tags %}


{% block content %}

<div class="shop-list">

{% for shop in shops %}


<div class="row"><div class="col-md-12">
	<div class="shop-info">
		<div class="row">
			<div class="col-md-3 col-sm-4 image-wrapper">
				<a href='{{ shop.get_absolute_url }}'>
					<img src="{{ shop.image.thumb100 }}"></a>
			</div>
			<div class="col-md-9 col-sm-8">
				<h5>{{ shop }}</h5>
				<div class="shop-contacts">

					{% if shop.site %}
					<p class="site" data-icon="&#xe08d;">
						{{ shop.site }}
					</p>
					{% endif %}

					{% if shop.use_custom_adress %}
					{% if shop.custom_adress %}
					<p class="adress"  data-icon="&#xe096;">
						<span>{{ shop.custom_adress }}</span>
						{% endif %}
					</p> 
					{% else %}
					<p class="adress" data-icon="&#xe096;">
						<span>
						{{ shop.city }}
						{{ shop.region }}
						{{ shop.area }}
						{{ shop.street }}
						{{ shop.house }}
						{{ shop.building }}
						{{ shop.flat }}
						{{ shop.index }}
						{{ shop.settlement }}
						{% endif %}
						</span>
					</p>
					{% if shop.phones.all.exists %}
					<p class="phone" data-icon="&#xe048;">
						<span>
							{% for phone in shop.phones.all %}
							{{ phone }} <br />
							{% endfor %}
						</span>
						{% endif %}
					</p>

					{% if shop.work_time %}
					<p class="time">Время работы: {{ shop.work_time }}</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	</div></div>






{% endfor %}

{% if shops.count > 0 %}
{% include 'discount/general/_pager.html' %}

{% endif %}


</div>

{% endblock content %}